import PlacementCompany from "../models/PlacementCompany.js";
import PlacementQuestion from "../models/PlacementQuestion.js";
import { APTITUDE_QUESTIONS, TECHNICAL_QUESTIONS } from "./placementQuestionsData.js";
import { CODING_QUESTIONS } from "./placementCodingQuestionsData.js";
import { NEW_MNC_QUESTIONS } from "./newMncQuestionsData.js";
import { PLACEMENT_2026_QUESTIONS, CODING_2026_QUESTIONS } from "./newPlacement2026Data.js";
import { INTERVIEW_QUESTIONS_DATA } from "./interviewQuestionsData.js";

export const COMPANIES_DATA = [
  {
    slug: "google",
    name: "Google",
    logo: "https://www.vectorlogo.zone/logos/google/google-icon.svg",
    description: "Leading technology titan known for search, cloud computing, AI, and cutting-edge software engineering.",
    tier: "FAANG / Top Product",
    hiringRoles: ["Software Engineer (L3)", "Associate Software Engineer", "Data Engineer", "Cloud Solutions Engineer"],
    rounds: [
      { name: "Online Assessment (OA)", type: "Online Assessment", description: "2 complex algorithmic coding problems on graphs, DP, or trees.", duration: "90 mins" },
      { name: "Technical Round 1", type: "Technical Interview", description: "DSA & Problem Solving with optimal time/space complexity analysis.", duration: "45 mins" },
      { name: "Technical Round 2", type: "Technical Interview", description: "Advanced Data Structures, algorithms, and system modularity.", duration: "45 mins" },
      { name: "Technical Round 3", type: "Technical Interview", description: "Low-Level Design / Data Structures / Core CS fundamentals.", duration: "45 mins" },
      { name: "Googliness & Leadership", type: "HR / Behavioral", description: "Behavioral questions testing collaboration, ethics, and culture fit.", duration: "45 mins" },
    ],
    popular: true,
    active: true,
    stats: { totalQuestions: 65, totalCoding: 22, avgPackage: "35-55 LPA", difficulty: "Hard" },
    order: 1,
  },
  {
    slug: "microsoft",
    name: "Microsoft",
    logo: "https://www.vectorlogo.zone/logos/microsoft/microsoft-icon.svg",
    description: "Global cloud, software, gaming, and enterprise giant known for Azure, Windows, GitHub, and AI systems.",
    tier: "FAANG / Top Product",
    hiringRoles: ["Software Development Engineer (SDE-1)", "Support Engineer", "Cloud Solution Architect"],
    rounds: [
      { name: "Online Assessment", type: "Online Assessment", description: "3 coding questions + debugging & CS MCQs.", duration: "90 mins" },
      { name: "Technical Interview 1", type: "Technical Interview", description: "Data Structures, Trees, Strings, and Linked Lists.", duration: "60 mins" },
      { name: "Technical Interview 2", type: "Technical Interview", description: "Dynamic Programming, Graphs, and CS Core (OS, DBMS).", duration: "60 mins" },
      { name: "AA (As Appropriate) / Managerial", type: "Managerial", description: "High-level design, project deep-dive, and behavioral alignment.", duration: "45 mins" },
    ],
    popular: true,
    active: true,
    stats: { totalQuestions: 60, totalCoding: 18, avgPackage: "28-48 LPA", difficulty: "Medium-Hard" },
    order: 2,
  },
  {
    slug: "amazon",
    name: "Amazon",
    logo: "https://www.vectorlogo.zone/logos/amazon/amazon-icon.svg",
    description: "E-commerce and cloud computing behemoth focusing heavily on Leadership Principles and high-scale systems.",
    tier: "FAANG / Top Product",
    hiringRoles: ["SDE-1", "Software Engineer - AWS", "Operations Tech Engineer"],
    rounds: [
      { name: "Amazon OA1 & OA2", type: "Online Assessment", description: "2 Coding Questions + Work Style Assessment & LP questions.", duration: "90 mins" },
      { name: "Technical Bar Raiser 1", type: "Technical Interview", description: "Coding (Arrays, HashMaps, Two Pointers) + 2 Amazon Leadership Principles.", duration: "60 mins" },
      { name: "Technical Bar Raiser 2", type: "Technical Interview", description: "Trees, Graphs, Recursion + 2 Leadership Principles.", duration: "60 mins" },
      { name: "Hiring Manager Round", type: "HR / Behavioral", description: "STAR method behavioral questions & Project architecture.", duration: "60 mins" },
    ],
    popular: true,
    active: true,
    stats: { totalQuestions: 68, totalCoding: 22, avgPackage: "30-50 LPA", difficulty: "Medium-Hard" },
    order: 3,
  },
  {
    slug: "meta",
    name: "Meta",
    logo: "https://www.vectorlogo.zone/logos/meta/meta-icon.svg",
    description: "World-class social technology and AI infrastructure company behind Instagram, WhatsApp, and LLaMA.",
    tier: "FAANG / Top Product",
    hiringRoles: ["Software Engineer (E3)", "Production Engineer", "Systems Specialist"],
    rounds: [
      { name: "Initial Technical Screen", type: "Technical Interview", description: "2 fast-paced LeetCode Medium/Hard questions.", duration: "45 mins" },
      { name: "Onsite Coding 1", type: "Technical Interview", description: "Advanced DSA, speed, accuracy, and edge-case handling.", duration: "45 mins" },
      { name: "Onsite Coding 2", type: "Technical Interview", description: "Graph algorithms, sliding window, and recursion.", duration: "45 mins" },
      { name: "Behavioral & Cultural", type: "HR / Behavioral", description: "Past impact, conflict resolution, and leadership traits.", duration: "45 mins" },
    ],
    popular: true,
    active: true,
    stats: { totalQuestions: 55, totalCoding: 18, avgPackage: "35-58 LPA", difficulty: "Hard" },
    order: 4,
  },
  {
    slug: "adobe",
    name: "Adobe",
    logo: "https://www.vectorlogo.zone/logos/adobe/adobe-icon.svg",
    description: "Creative cloud, document productivity, and digital experience software leader.",
    tier: "Product Giant",
    hiringRoles: ["Software Engineer - Product", "Associate Software Engineer", "Computer Scientist 1"],
    rounds: [
      { name: "Online Test", type: "Online Assessment", description: "Aptitude + CS Fundamentals MCQs + 2 Coding Problems.", duration: "90 mins" },
      { name: "Technical Round 1", type: "Technical Interview", description: "DSA, OOP design patterns, and C++/Java fundamentals.", duration: "60 mins" },
      { name: "Technical Round 2", type: "Technical Interview", description: "Trees, Tries, Graphs, and DBMS optimization.", duration: "60 mins" },
      { name: "HR & Director Round", type: "HR / Behavioral", description: "Project defense and values alignment.", duration: "45 mins" },
    ],
    popular: true,
    active: true,
    stats: { totalQuestions: 55, totalCoding: 16, avgPackage: "22-42 LPA", difficulty: "Medium-Hard" },
    order: 5,
  },
  {
    slug: "tcs",
    name: "TCS",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b1/Tata_Consultancy_Services_Logo.svg/512px-Tata_Consultancy_Services_Logo.svg.png",
    description: "Tata Consultancy Services — India's largest IT multinational offering Ninja (3.6 LPA), Digital (7.5 LPA), and Prime (9-11 LPA) hiring cadres.",
    tier: "IT & Consulting Leader",
    hiringRoles: ["TCS Ninja (3.6 LPA)", "TCS Digital (7.5 LPA)", "TCS Prime (9-11 LPA)"],
    rounds: [
      { name: "TCS NQT Foundation", type: "Online Assessment", description: "Numerical Ability, Verbal Ability & Reasoning Ability (Ninja/Digital/Prime Qualifier).", duration: "75 mins" },
      { name: "TCS NQT Advanced", type: "Online Assessment", description: "Advanced Quantitative, Advanced Reasoning & 2 Coding Questions for Digital/Prime.", duration: "90 mins" },
      { name: "Technical Interview", type: "Technical Interview", description: "DSA, C/Java/Python, SQL Queries, OOPs & Final Year Project.", duration: "35 mins" },
      { name: "Managerial & HR Interview", type: "HR / Behavioral", description: "Workplace scenarios, career goals, relocation flexibility.", duration: "20 mins" },
    ],
    popular: true,
    active: true,
    stats: { totalQuestions: 75, totalCoding: 16, avgPackage: "4-11 LPA", difficulty: "Easy-Medium" },
    order: 6,
  },
  {
    slug: "infosys",
    name: "Infosys",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/95/Infosys_logo.svg/512px-Infosys_logo.svg.png",
    description: "Global consulting and information technology powerhouse hiring for System Engineer, DSE, and Specialist Programmer.",
    tier: "IT & Consulting Leader",
    hiringRoles: ["System Engineer (SE)", "Digital Specialist Engineer (DSE)", "Specialist Programmer (SP)"],
    rounds: [
      { name: "Infosys Online Test", type: "Online Assessment", description: "Reasoning Ability, Mathematical Ability, Verbal Ability, Pseudocode & Puzzle Solving.", duration: "100 mins" },
      { name: "Hands-on Coding (SP/DSE)", type: "Online Assessment", description: "3 Advanced DSA problems on DP, Graph Traversal & Greedy Algorithms.", duration: "180 mins" },
      { name: "Technical & HR Interview", type: "Technical Interview", description: "Data Structures, Database Management Systems, Projects & Behavioral fit.", duration: "40 mins" },
    ],
    popular: true,
    active: true,
    stats: { totalQuestions: 70, totalCoding: 15, avgPackage: "4-9.5 LPA", difficulty: "Easy-Medium" },
    order: 7,
  },
  {
    slug: "wipro",
    name: "Wipro",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a0/Wipro_Primary_Logo_Color_RGB.svg/512px-Wipro_Primary_Logo_Color_RGB.svg.png",
    description: "Leading technology services and consulting company offering Elite National Talent Hunt and Turbo career tracks.",
    tier: "IT & Consulting Leader",
    hiringRoles: ["Project Engineer - Elite", "Turbo Candidate", "Cloud Associate"],
    rounds: [
      { name: "National Qualifier Test", type: "Online Assessment", description: "Aptitude, Logical Reasoning, Verbal, Essay Writing, and Automata Fix / Debugging Coding.", duration: "120 mins" },
      { name: "Combined Tech + HR Interview", type: "Technical Interview", description: "Core CS, language fundamentals, code walkthrough, and behavioral alignment.", duration: "30 mins" },
    ],
    popular: false,
    active: true,
    stats: { totalQuestions: 58, totalCoding: 13, avgPackage: "3.5-7 LPA", difficulty: "Easy-Medium" },
    order: 8,
  },
  {
    slug: "accenture",
    name: "Accenture",
    logo: "https://www.vectorlogo.zone/logos/accenture/accenture-icon.svg",
    description: "Global professional services company with leading capabilities in digital, cloud, security, and enterprise strategy.",
    tier: "IT & Consulting Leader",
    hiringRoles: ["Associate Software Engineer (ASE)", "Advanced Associate Software Engineer (AASE)"],
    rounds: [
      { name: "Cognitive & Technical Assessment", type: "Online Assessment", description: "English Ability, Critical Thinking, Abstract Reasoning, Common Applications, MS Office, Pseudocode & Network Security.", duration: "90 mins" },
      { name: "Coding Assessment", type: "Online Assessment", description: "2 Hands-on Coding questions (Binary string / array problems in C++/Java/Python).", duration: "45 mins" },
      { name: "Communication Assessment", type: "Online Assessment", description: "AI-proctored spoken English, sentence repetition, reading fluency & comprehension.", duration: "20 mins" },
      { name: "HR & Technical Interview", type: "HR / Behavioral", description: "Project deep-dive, technical fundamentals, and behavioral questions.", duration: "30 mins" },
    ],
    popular: true,
    active: true,
    stats: { totalQuestions: 68, totalCoding: 16, avgPackage: "4.5-8.5 LPA", difficulty: "Easy-Medium" },
    order: 9,
  },
  {
    slug: "deloitte",
    name: "Deloitte",
    logo: "https://www.vectorlogo.zone/logos/deloitte/deloitte-icon.svg",
    description: "Top consulting firm providing audit, consulting, financial advisory, risk advisory, and technology engineering.",
    tier: "IT & Consulting Leader",
    hiringRoles: ["Analyst - Technology Consulting", "Associate Solution Advisor"],
    rounds: [
      { name: "Online Assessment", type: "Online Assessment", description: "Quantitative, Logical, Verbal, Computer Fundamentals, and Coding.", duration: "95 mins" },
      { name: "Technical Interview", type: "Technical Interview", description: "SQL, DBMS, OOP, problem solving, and analytical thinking.", duration: "40 mins" },
      { name: "Partner / HR Round", type: "HR / Behavioral", description: "Consulting mindset, client handling, and case studies.", duration: "30 mins" },
    ],
    popular: false,
    active: true,
    stats: { totalQuestions: 56, totalCoding: 12, avgPackage: "7.5-12 LPA", difficulty: "Medium" },
    order: 10,
  },
  {
    slug: "cognizant",
    name: "Cognizant",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/23/Cognizant_logo_2022.svg/512px-Cognizant_logo_2022.svg.png",
    description: "Multinational information technology services and consulting provider offering GenC, GenC Elevate, and GenC Next tracks.",
    tier: "IT & Consulting Leader",
    hiringRoles: ["GenC", "GenC Elevate", "GenC Next"],
    rounds: [
      { name: "Communication Assessment", type: "Online Assessment", description: "Automated AI listening, spoken English, and comprehension test.", duration: "30 mins" },
      { name: "Skill & Coding Assessment", type: "Online Assessment", description: "Quantitative, Analytical, Core CS MCQs (OS, DBMS, SQL) & 2 Coding Problems.", duration: "100 mins" },
      { name: "Technical & HR Interview", type: "Technical Interview", description: "Java/Python, DBMS, SQL joins, DSA and project architecture.", duration: "35 mins" },
    ],
    popular: false,
    active: true,
    stats: { totalQuestions: 58, totalCoding: 13, avgPackage: "4-7.5 LPA", difficulty: "Easy-Medium" },
    order: 11,
  },
  {
    slug: "capgemini",
    name: "Capgemini",
    logo: "https://www.vectorlogo.zone/logos/capgemini/capgemini-icon.svg",
    description: "Global leader in digital transformation and technology consulting hiring Software Analysts with a newly updated assessment pipeline.",
    tier: "IT & Consulting Leader",
    hiringRoles: ["Software Analyst (4.25 LPA)", "Senior Software Analyst (5.75 - 7.5 LPA)"],
    rounds: [
      { name: "Round 1: Foundation & AI Assessment", type: "Online Assessment", description: "Combined Versant English Communication, AI Literacy & Generative AI fundamentals, and Cognitive Game tests.", duration: "40 mins" },
      { name: "Round 2: Hands-On Debugging Round", type: "Online Assessment", description: "Interactive compiler round: identify and fix preloaded bugs in Java, Python, C++, and JS.", duration: "30 mins" },
      { name: "Round 3: AI-Assisted Coding Round", type: "Online Assessment", description: "Solve algorithmic problem statements with Copilot prompt strategies & Monaco test runner.", duration: "45 mins" },
      { name: "Round 4: Technical & HR Interview", type: "Technical Interview", description: "Resume defense, project deep-dive, core CS fundamentals, and STAR behavioral round.", duration: "40 mins" },
    ],
    popular: true,
    active: true,
    stats: { totalQuestions: 65, totalCoding: 15, avgPackage: "4.25-7.5 LPA", difficulty: "Easy-Medium" },
    order: 12,
  },
  {
    slug: "apple",
    name: "Apple",
    logo: "https://www.vectorlogo.zone/logos/apple/apple-icon.svg",
    description: "Global consumer electronics, iOS/macOS systems, hardware architecture, and silicon engineering titan.",
    tier: "FAANG / Top Product",
    hiringRoles: ["Software Engineer - CoreOS", "iOS Engineer", "Systems Software Specialist", "Tools & Frameworks Engineer"],
    rounds: [
      { name: "Technical Screen", type: "Technical Interview", description: "C/C++, Data Structures, Memory Management, and OS Concepts.", duration: "60 mins" },
      { name: "Onsite Technical 1", type: "Technical Interview", description: "Advanced Algorithms, Concurrency, and System Optimization.", duration: "60 mins" },
      { name: "Onsite Technical 2", type: "Technical Interview", description: "Low-Level Design & Code Execution under constraints.", duration: "60 mins" },
      { name: "Team Fit & Managerial", type: "Managerial", description: "Design philosophy, attention to detail, and behavioral deep-dive.", duration: "45 mins" },
    ],
    popular: true,
    active: true,
    stats: { totalQuestions: 62, totalCoding: 20, avgPackage: "35-65 LPA", difficulty: "Hard" },
    order: 13,
  },
  {
    slug: "netflix",
    name: "Netflix",
    logo: "https://www.vectorlogo.zone/logos/netflix/netflix-icon.svg",
    description: "Streaming entertainment pioneer known for high-concurrency microservices, distributed systems, and freedom & responsibility culture.",
    tier: "FAANG / Top Product",
    hiringRoles: ["Software Engineer (L4/L5)", "Data Platform Engineer", "Cloud Infrastructure Engineer"],
    rounds: [
      { name: "Online Code Screen", type: "Online Assessment", description: "2 Hard algorithmic challenges with extreme scale edge-cases.", duration: "90 mins" },
      { name: "Distributed Systems & DSA", type: "Technical Interview", description: "High-throughput data pipelines, caching, and tree/graph problems.", duration: "60 mins" },
      { name: "System Architecture", type: "System Design", description: "Large-scale video streaming pipelines & fault tolerance.", duration: "60 mins" },
      { name: "Culture Memo Discussion", type: "HR / Behavioral", description: "Deep alignment with Netflix Culture: Impact, Candor, and Judgment.", duration: "45 mins" },
    ],
    popular: true,
    active: true,
    stats: { totalQuestions: 58, totalCoding: 19, avgPackage: "45-75 LPA", difficulty: "Hard" },
    order: 14,
  },
  {
    slug: "oracle",
    name: "Oracle",
    logo: "https://www.vectorlogo.zone/logos/oracle/oracle-icon.svg",
    description: "Enterprise software, Autonomous Database, and Oracle Cloud Infrastructure (OCI) engineering giant.",
    tier: "Product Giant",
    hiringRoles: ["Member of Technical Staff (MTS)", "Software Developer 1", "Cloud Engineer - OCI"],
    rounds: [
      { name: "Oracle OA", type: "Online Assessment", description: "CS Fundamentals (OS, DBMS, OOP) + 2 Coding Problems.", duration: "105 mins" },
      { name: "Technical Round 1", type: "Technical Interview", description: "DSA, DBMS internals, SQL queries, and Java/C++ basics.", duration: "60 mins" },
      { name: "Technical Round 2", type: "Technical Interview", description: "Trees, Graphs, Operating Systems, and Multithreading.", duration: "60 mins" },
      { name: "Director / HR Round", type: "HR / Behavioral", description: "Resume review, projects defense, and company alignment.", duration: "40 mins" },
    ],
    popular: true,
    active: true,
    stats: { totalQuestions: 64, totalCoding: 16, avgPackage: "20-40 LPA", difficulty: "Medium-Hard" },
    order: 15,
  },
  {
    slug: "goldman-sachs",
    name: "Goldman Sachs",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/61/Goldman_Sachs.svg/512px-Goldman_Sachs.svg.png",
    description: "Premier global investment banking, securities, and investment management firm with world-class engineering teams.",
    tier: "Fintech & Startups",
    hiringRoles: ["New Analyst - Engineering", "Quantitative Developer", "Software Engineer - Core Engineering"],
    rounds: [
      { name: "Aptitude & Coding OA", type: "Online Assessment", description: "Numerical Ability, Advanced Math, CS MCQs & 2 Coding Questions.", duration: "135 mins" },
      { name: "Technical Interview 1", type: "Technical Interview", description: "DSA (Trees, DP, Arrays), Probability, and Logic Puzzles.", duration: "60 mins" },
      { name: "Technical Interview 2", type: "Technical Interview", description: "Object Oriented Design, System Optimization, and SQL.", duration: "60 mins" },
      { name: "Senior Partner / Behavioral", type: "HR / Behavioral", description: "High-pressure decision making, integrity, and team collaboration.", duration: "45 mins" },
    ],
    popular: true,
    active: true,
    stats: { totalQuestions: 66, totalCoding: 18, avgPackage: "28-52 LPA", difficulty: "Hard" },
    order: 16,
  },
  {
    slug: "jpmorgan",
    name: "JPMorgan Chase",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/af/J_P_Morgan_Chase_Logo_2008_1.svg/512px-J_P_Morgan_Chase_Logo_2008_1.svg.png",
    description: "Global financial services leader building massive payment rails, cloud architectures, and cybersecurity systems.",
    tier: "Fintech & Startups",
    hiringRoles: ["Software Engineer Program (SEP)", "Applied AI Engineer", "Cloud Associate"],
    rounds: [
      { name: "Code for Good / HackerRank OA", type: "Online Assessment", description: "2 Coding problems + Video behavioral prompts (HireVue).", duration: "90 mins" },
      { name: "Technical Interview 1", type: "Technical Interview", description: "Data Structures, Algorithms, and Software Engineering Principles.", duration: "45 mins" },
      { name: "Technical Interview 2", type: "Technical Interview", description: "System architecture, API design, and Database schemas.", duration: "45 mins" },
      { name: "Culture & HR", type: "HR / Behavioral", description: "JPMorgan Chase core values, adaptability, and teamwork.", duration: "30 mins" },
    ],
    popular: true,
    active: true,
    stats: { totalQuestions: 60, totalCoding: 15, avgPackage: "20-38 LPA", difficulty: "Medium-Hard" },
    order: 17,
  },
  {
    slug: "cisco",
    name: "Cisco",
    logo: "https://www.vectorlogo.zone/logos/cisco/cisco-icon.svg",
    description: "Worldwide technology leader that powers the Internet with networking, cloud, and cybersecurity systems.",
    tier: "Product Giant",
    hiringRoles: ["Software Engineer (Core)", "Cloud & Network Engineer", "Security Analyst"],
    rounds: [
      { name: "Online Assessment", type: "Online Assessment", description: "Aptitude, Computer Networks MCQs, OS & 2 Coding Problems.", duration: "90 mins" },
      { name: "Technical Round 1", type: "Technical Interview", description: "TCP/IP, OSI model, Socket programming, and DSA.", duration: "60 mins" },
      { name: "Technical Round 2", type: "Technical Interview", description: "Operating Systems, Concurrency, and System Design.", duration: "45 mins" },
      { name: "Managerial & HR", type: "HR / Behavioral", description: "Behavioral and situational questions.", duration: "30 mins" },
    ],
    popular: false,
    active: true,
    stats: { totalQuestions: 56, totalCoding: 14, avgPackage: "18-35 LPA", difficulty: "Medium-Hard" },
    order: 18,
  },
  {
    slug: "uber",
    name: "Uber",
    logo: "https://www.vectorlogo.zone/logos/uber/uber-icon.svg",
    description: "Global mobility and delivery platform known for real-time dispatch systems, geospatial indexing, and extreme scale.",
    tier: "Product Giant",
    hiringRoles: ["Software Engineer 1 (SE-1)", "Backend Engineer", "Infrastructure Specialist"],
    rounds: [
      { name: "Uber OA (CodeSignal)", type: "Online Assessment", description: "4 fast-paced algorithmic coding problems.", duration: "70 mins" },
      { name: "Coding Round 1", type: "Technical Interview", description: "Advanced DSA (Intervals, Heaps, Graph BFS/DFS).", duration: "60 mins" },
      { name: "Coding Round 2", type: "Technical Interview", description: "Real-world algorithmic problem solving with optimal complexity.", duration: "60 mins" },
      { name: "Bar Raiser & Behavioral", type: "HR / Behavioral", description: "Uber values: Go Get It, Trip Up, Customer Obsession.", duration: "45 mins" },
    ],
    popular: true,
    active: true,
    stats: { totalQuestions: 62, totalCoding: 20, avgPackage: "32-60 LPA", difficulty: "Hard" },
    order: 19,
  },
  {
    slug: "ibm",
    name: "IBM",
    logo: "https://www.vectorlogo.zone/logos/ibm/ibm-icon.svg",
    description: "Global cloud, cognitive solutions, Red Hat enterprise Linux, and AI consulting leader.",
    tier: "IT & Consulting Leader",
    hiringRoles: ["Associate System Engineer (ASE)", "Software Developer - Cloud", "AI Engineer"],
    rounds: [
      { name: "Cognitive Ability & Coding", type: "Online Assessment", description: "Cognitive mini-games, English assessment, and 1 Coding problem.", duration: "90 mins" },
      { name: "Technical Interview", type: "Technical Interview", description: "Python/Java, Cloud fundamentals, OOPs, and Academic Project.", duration: "45 mins" },
      { name: "HR Interview", type: "HR / Behavioral", description: "Teamwork, communication, and flexibility.", duration: "20 mins" },
    ],
    popular: false,
    active: true,
    stats: { totalQuestions: 54, totalCoding: 12, avgPackage: "6-14 LPA", difficulty: "Easy-Medium" },
    order: 20,
  },
  {
    slug: "salesforce",
    name: "Salesforce",
    logo: "https://www.vectorlogo.zone/logos/salesforce/salesforce-icon.svg",
    description: "World #1 CRM and enterprise cloud platform powering digital business transformations.",
    tier: "Product Giant",
    hiringRoles: ["Associate Member of Technical Staff (AMTS)", "Software Engineer"],
    rounds: [
      { name: "Online Coding Test", type: "Online Assessment", description: "3 algorithmic coding questions (Hackerrank).", duration: "90 mins" },
      { name: "Technical Interview 1", type: "Technical Interview", description: "DSA, HashMaps, Trees, and Dynamic Programming.", duration: "60 mins" },
      { name: "Technical Interview 2", type: "Technical Interview", description: "OOPs design, database schemas, and REST APIs.", duration: "60 mins" },
      { name: "Hiring Manager Round", type: "HR / Behavioral", description: "Ohana culture, past projects, and behavioral scenarios.", duration: "45 mins" },
    ],
    popular: true,
    active: true,
    stats: { totalQuestions: 60, totalCoding: 17, avgPackage: "25-48 LPA", difficulty: "Medium-Hard" },
    order: 21,
  },
  {
    slug: "qualcomm",
    name: "Qualcomm",
    logo: "https://www.vectorlogo.zone/logos/qualcomm/qualcomm-icon.svg",
    description: "World leader in wireless technology, Snapdragon mobile processors, 5G modems, and edge AI compute.",
    tier: "Product Giant",
    hiringRoles: ["Engineer - Software", "Embedded Systems Developer", "Modem Software Engineer"],
    rounds: [
      { name: "Qualcomm OA", type: "Online Assessment", description: "Aptitude, C/C++ Pointers & Bit Manipulation MCQs, OS, and 2 Coding Problems.", duration: "90 mins" },
      { name: "Technical Round 1", type: "Technical Interview", description: "C programming, Pointers, Memory Management, Bitwise tricks, DSA.", duration: "60 mins" },
      { name: "Technical Round 2", type: "Technical Interview", description: "OS concepts (Semaphores, Mutex, Scheduling, Virtual Memory).", duration: "60 mins" },
      { name: "HR Round", type: "HR / Behavioral", description: "Cultural fit, career aspirations, and team dynamics.", duration: "30 mins" },
    ],
    popular: false,
    active: true,
    stats: { totalQuestions: 58, totalCoding: 15, avgPackage: "22-42 LPA", difficulty: "Medium-Hard" },
    order: 22,
  },
];

export const SAMPLE_QUESTIONS = [
  // ───────────────────────────────────────────────────────────────────────────
  // 1. APTITUDE QUESTIONS (Quantitative & Logical Reasoning)
  // ───────────────────────────────────────────────────────────────────────────
  {
    title: "Train Passing a Platform",
    category: "aptitude",
    type: "mcq",
    difficulty: "Easy",
    companies: ["tcs", "infosys", "wipro", "accenture", "deloitte", "cognizant", "capgemini"],
    topics: ["Time, Speed & Distance", "Trains"],
    frequency: "High",
    source: "Reported in TCS, Infosys & Accenture Online Assessments",
    tags: ["OA", "Quantitative Aptitude", "2025", "2026"],
    lastReviewed: "2026",
    description: "A train 150 meters long is running at a speed of 54 km/hr. How much time (in seconds) will it take to cross a platform 250 meters long?",
    options: ["20.5 seconds", "26.67 seconds", "24.0 seconds", "30.0 seconds"],
    correctAnswer: 1,
    formula: "Speed in m/s = Speed in km/hr × (5/18); Time = Total Distance / Speed",
    explanation: "1. Convert speed to m/s: 54 × (5/18) = 15 m/s.\n2. Total distance = Length of train + Length of platform = 150 + 250 = 400 meters.\n3. Time taken = Total Distance / Speed = 400 / 15 = 26.67 seconds.",
  },
  {
    title: "Profit and Loss with Successive Discounts",
    category: "aptitude",
    type: "mcq",
    difficulty: "Medium",
    companies: ["google", "amazon", "adobe", "deloitte", "accenture", "microsoft"],
    topics: ["Profit & Loss", "Percentages"],
    frequency: "High",
    source: "Reported in Amazon & Deloitte Quantitative sections",
    tags: ["OA", "Percentages", "2026"],
    lastReviewed: "2026",
    description: "A shopkeeper marks an article 40% above the cost price and allows two successive discounts of 15% and 10% on the marked price. What is his overall gain or loss percentage?",
    options: ["Gain of 7.1%", "Gain of 5.5%", "Loss of 2.4%", "Gain of 8.0%"],
    correctAnswer: 0,
    formula: "Net SP = CP × (1 + Markup%) × (1 - D1%) × (1 - D2%)",
    explanation: "1. Assume CP = 100.\n2. Marked Price (MP) = 100 + 40 = 140.\n3. First discount of 15%: Price = 140 × (1 - 0.15) = 140 × 0.85 = 119.\n4. Second discount of 10%: SP = 119 × (1 - 0.10) = 119 × 0.90 = 107.1.\n5. Gain = SP - CP = 107.1 - 100 = 7.1, so Gain % = 7.1%.",
  },
  {
    title: "Work Efficiency & Alternating Days",
    category: "aptitude",
    type: "mcq",
    difficulty: "Medium",
    companies: ["tcs", "infosys", "microsoft", "amazon", "capgemini", "wipro"],
    topics: ["Time & Work"],
    frequency: "High",
    source: "Reported in TCS Digital & Infosys SP Assessments",
    tags: ["OA", "Time & Work", "2025", "2026"],
    lastReviewed: "2026",
    description: "A can complete a piece of work in 12 days, and B can complete the same work in 18 days. If they work on alternate days starting with A on the first day, in how many days will the entire work be completed?",
    options: ["14 1/3 days", "14 1/2 days", "15 days", "13 2/3 days"],
    correctAnswer: 0,
    formula: "Total Work = LCM(12, 18) = 36 units. Efficiency: A = 3 u/day, B = 2 u/day.",
    explanation: "1. Total Work = LCM(12, 18) = 36 units.\n2. Efficiency of A = 36 / 12 = 3 units/day; Efficiency of B = 36 / 18 = 2 units/day.\n3. In a 2-day cycle (Day 1: A, Day 2: B), work done = 3 + 2 = 5 units.\n4. In 7 cycles (14 days), work completed = 7 × 5 = 35 units.\n5. Remaining work = 36 - 35 = 1 unit.\n6. On Day 15, A works: time taken for 1 unit = 1/3 day.\n7. Total time = 14 + 1/3 = 14 1/3 days.",
  },
  {
    title: "Probability of Non-Defective Items",
    category: "aptitude",
    type: "mcq",
    difficulty: "Hard",
    companies: ["google", "microsoft", "amazon", "adobe", "meta"],
    topics: ["Probability", "Permutation & Combination"],
    frequency: "Medium",
    source: "Reported in Google & Amazon Online Assessments",
    tags: ["OA", "Probability", "2026"],
    lastReviewed: "2026",
    description: "A box contains 8 red balls and 6 green balls. If 3 balls are drawn at random one after another without replacement, what is the probability that at least 2 of the drawn balls are red?",
    options: ["34/91", "56/91 (8/13)", "28/91", "68/91"],
    correctAnswer: 1,
    formula: "P(At least 2 Red) = [C(8,2)×C(6,1) + C(8,3)×C(6,0)] / C(14,3)",
    explanation: "1. Total outcomes = C(14,3) = (14×13×12)/6 = 364.\n2. Exactly 2 Red & 1 Green = C(8,2) × C(6,1) = 28 × 6 = 168.\n3. Exactly 3 Red = C(8,3) = 56.\n4. Total favorable = 168 + 56 = 224.\n5. P = 224 / 364 = 56 / 91 = 8 / 13.",
  },
  {
    title: "Pipes and Cisterns with a Leak",
    category: "aptitude",
    type: "mcq",
    difficulty: "Medium",
    companies: ["tcs", "infosys", "wipro", "capgemini", "accenture", "deloitte"],
    topics: ["Time & Work", "Pipes & Cisterns"],
    frequency: "High",
    source: "Reported in Infosys & Wipro Elite assessments",
    tags: ["OA", "Time & Work", "2026"],
    lastReviewed: "2026",
    description: "A pipe can fill a water tank in 8 hours. Due to a leak at the bottom, it takes 10 hours to fill the tank. If the tank is completely full, in how many hours will the leak empty it alone?",
    options: ["30 hours", "40 hours", "45 hours", "50 hours"],
    correctAnswer: 1,
    formula: "Work done by leak in 1 hour = (1 / Fill time without leak) - (1 / Fill time with leak)",
    explanation: "1. Filling rate = 1/8 tank/hour.\n2. Net rate with leak = 1/10 tank/hour.\n3. Leak rate = 1/8 - 1/10 = (5 - 4) / 40 = 1/40 tank/hour.\n4. Therefore, the leak alone will empty the full tank in 40 hours.",
  },
  {
    title: "Boats and Streams - Relative Velocity",
    category: "aptitude",
    type: "mcq",
    difficulty: "Medium",
    companies: ["tcs", "infosys", "deloitte", "cognizant", "amazon"],
    topics: ["Time, Speed & Distance", "Boats & Streams"],
    frequency: "High",
    source: "Reported in TCS Digital & Deloitte Quantitative round",
    tags: ["OA", "Time, Speed & Distance", "2026"],
    lastReviewed: "2026",
    description: "A boat travels 24 km upstream in 6 hours and 36 km downstream in 4 hours. What is the speed of the current (stream) in km/hr?",
    options: ["1.5 km/hr", "2.5 km/hr", "3.0 km/hr", "2.0 km/hr"],
    correctAnswer: 1,
    formula: "Speed upstream (U) = Distance/Time; Speed downstream (D) = Distance/Time; Speed of Stream = (D - U) / 2",
    explanation: "1. Upstream Speed (U) = 24 / 6 = 4 km/hr.\n2. Downstream Speed (D) = 36 / 4 = 9 km/hr.\n3. Speed of Current = (D - U) / 2 = (9 - 4) / 2 = 5 / 2 = 2.5 km/hr.",
  },
  {
    title: "Permutations - Words with Vowels Together",
    category: "aptitude",
    type: "mcq",
    difficulty: "Medium",
    companies: ["google", "amazon", "microsoft", "adobe", "tcs"],
    topics: ["Permutation & Combination"],
    frequency: "High",
    source: "Reported in Google & Adobe OA assessments",
    tags: ["OA", "Permutations", "2026"],
    lastReviewed: "2026",
    description: "In how many distinct ways can the letters of the word 'LEADER' be arranged such that all vowels are always together?",
    options: ["72", "144", "108", "216"],
    correctAnswer: 0,
    formula: "Bundle vowels into 1 unit: (Total items)! / (repeats)! × (Vowels)! / (vowel repeats)!",
    explanation: "1. In 'LEADER', letters are L, E, A, D, E, R (6 letters). Vowels: E, A, E (3 vowels with 2 E's). Consonants: L, D, R (3 consonants).\n2. Bundle vowels as one block [EAE] + 3 consonants = 4 entities.\n3. 4 entities can be arranged in 4! = 24 ways.\n4. The 3 vowels (E, A, E) can be arranged internally in 3! / 2! = 6 / 2 = 3 ways.\n5. Total arrangements = 24 × 3 = 72 ways.",
  },
  {
    title: "Ratio and Proportion - Coins in a Bag",
    category: "aptitude",
    type: "mcq",
    difficulty: "Easy",
    companies: ["tcs", "infosys", "wipro", "deloitte", "accenture"],
    topics: ["Ratio & Proportion"],
    frequency: "High",
    source: "Reported in TCS NQT & Wipro Elite",
    tags: ["OA", "Ratio & Proportion", "2026"],
    lastReviewed: "2026",
    description: "A bag contains coins in denominations of 50p, 25p, and 10p in the ratio 5 : 9 : 4, amounting to a total value of Rs. 206. Find the number of 50p coins.",
    options: ["180", "200", "220", "240"],
    correctAnswer: 1,
    formula: "Total Value = (5x × 0.50) + (9x × 0.25) + (4x × 0.10)",
    explanation: "1. Let number of coins be 5x, 9x, and 4x.\n2. Total value = (5x × 0.50) + (9x × 0.25) + (4x × 0.10) = 2.50x + 2.25x + 0.40x = 5.15x.\n3. 5.15x = 206 => x = 206 / 5.15 = 40.\n4. Number of 50p coins = 5x = 5 × 40 = 200 coins.",
  },

  // ───────────────────────────────────────────────────────────────────────────
  // 2. ENGLISH / VERBAL QUESTIONS
  // ───────────────────────────────────────────────────────────────────────────
  {
    title: "Subject-Verb Agreement with 'Neither...Nor'",
    category: "english",
    type: "mcq",
    difficulty: "Easy",
    companies: ["tcs", "infosys", "accenture", "wipro", "deloitte"],
    topics: ["Grammar", "Subject-Verb Agreement"],
    frequency: "High",
    source: "Reported in Accenture & TCS Verbal Ability assessments",
    tags: ["OA", "Verbal Ability", "Grammar", "2026"],
    lastReviewed: "2026",
    description: "Identify the grammatically correct sentence from the options below:",
    options: [
      "Neither the manager nor the employees was aware of the policy update.",
      "Neither the manager nor the employees were aware of the policy update.",
      "Neither the manager or the employees was aware of the policy update.",
      "Neither the manager nor the employees is aware of the policy update."
    ],
    correctAnswer: 1,
    formula: "Rule of Proximity: When subjects are joined by 'neither...nor', the verb agrees with the closer subject.",
    explanation: "In a 'neither...nor' construction, the verb agrees with the subject closest to it. Here, 'the employees' (plural) is closest to the verb, so the plural verb 'were' is required.",
  },
  {
    title: "Sentence Correction - Dangling Modifiers",
    category: "english",
    type: "mcq",
    difficulty: "Medium",
    companies: ["google", "microsoft", "amazon", "adobe", "deloitte"],
    topics: ["Sentence correction", "Grammar"],
    frequency: "High",
    source: "Reported in Deloitte & Amazon English screening",
    tags: ["OA", "Sentence Correction", "2026"],
    lastReviewed: "2026",
    description: "Choose the option that corrects the error: 'Having finished the assignment, the laptop was shut down by Alex.'",
    options: [
      "Having finished the assignment, the laptop was shut down by Alex.",
      "Having finished the assignment, Alex shut down the laptop.",
      "After finishing the assignment, the laptop was turned off by Alex.",
      "Finishing the assignment, Alex's laptop was shut down."
    ],
    correctAnswer: 1,
    formula: "Modifier Rule: An introductory participial phrase must modify the subject immediately following the comma.",
    explanation: "'Having finished the assignment' is a dangling modifier because a laptop cannot finish an assignment. The person who finished the assignment (Alex) must be the grammatical subject immediately following the comma.",
  },
  {
    title: "Vocabulary - High Frequency Synonyms (Ephemeral)",
    category: "english",
    type: "mcq",
    difficulty: "Medium",
    companies: ["google", "microsoft", "amazon", "adobe"],
    topics: ["Vocabulary", "Synonyms"],
    frequency: "High",
    source: "Reported in Google & Amazon verbal screening",
    tags: ["OA", "Vocabulary", "2026"],
    lastReviewed: "2026",
    description: "Select the word that is most nearly SIMILAR in meaning to 'EPHEMERAL':",
    options: ["Permanent", "Fleeting and Short-lived", "Enduring", "Monumental"],
    correctAnswer: 1,
    formula: "Ephemeral = lasting for a very short time; transitory.",
    explanation: "'Ephemeral' describes something transient or short-lived (e.g., ephemeral network state or temporary tokens). 'Fleeting and Short-lived' is the precise synonym.",
  },
  {
    title: "Sentence Fillers - Conjunctions (Despite vs In spite of)",
    category: "english",
    type: "mcq",
    difficulty: "Easy",
    companies: ["tcs", "accenture", "infosys", "wipro"],
    topics: ["Grammar", "Sentence Fillers"],
    frequency: "High",
    source: "Reported in TCS Digital & Accenture verbal",
    tags: ["OA", "Grammar", "2026"],
    lastReviewed: "2026",
    description: "Select the correct option to fill in the blank: '_______ severe network latency, the transaction completed successfully.'",
    options: ["Despite of", "In spite of", "Although", "Even though of"],
    correctAnswer: 1,
    formula: "'In spite of' and 'Despite' take noun phrases. 'Despite' never takes 'of'.",
    explanation: "'In spite of' is grammatically correct. 'Despite of' is incorrect because 'despite' is never followed by 'of'. 'Although' requires a full clause with a subject and verb.",
  },

  // ───────────────────────────────────────────────────────────────────────────
  // 3. TECHNICAL QUESTIONS (Core CS Fundamentals)
  // ───────────────────────────────────────────────────────────────────────────
  {
    title: "Data Structure for Breadth First Search (BFS)",
    category: "technical",
    type: "mcq",
    difficulty: "Easy",
    companies: ["google", "microsoft", "amazon", "meta", "adobe", "tcs", "infosys", "accenture"],
    topics: ["Data Structures", "Algorithms", "Graphs"],
    frequency: "High",
    source: "Reported across Google, Microsoft, TCS technical screening",
    tags: ["Technical Interview", "OA", "DSA", "2026"],
    lastReviewed: "2026",
    description: "Which data structure is standardly utilized to implement Breadth First Search (BFS) traversal on a graph or tree?",
    options: ["Stack (LIFO)", "Queue (FIFO)", "Priority Queue / Min-Heap", "Binary Search Tree"],
    correctAnswer: 1,
    explanation: "BFS explores nodes level by level (shallowest first). A Queue (First-In, First-Out) guarantees that nodes discovered first are visited and expanded first.",
  },
  {
    title: "DBMS ACID Properties - Isolation Levels",
    category: "technical",
    type: "mcq",
    difficulty: "Medium",
    companies: ["google", "microsoft", "amazon", "adobe", "tcs", "infosys"],
    topics: ["DBMS", "Transactions", "SQL"],
    frequency: "High",
    source: "Reported in Amazon SDE & Microsoft Technical Interviews",
    tags: ["Technical Interview", "DBMS", "2026"],
    lastReviewed: "2026",
    description: "Which transaction isolation level in SQL databases prevents 'Dirty Reads' and 'Non-Repeatable Reads', but may still permit 'Phantom Reads'?",
    options: ["Read Uncommitted", "Read Committed", "Repeatable Read", "Serializable"],
    correctAnswer: 2,
    explanation: "- Read Uncommitted: Allows dirty reads, non-repeatable reads, phantom reads.\n- Read Committed: Prevents dirty reads; allows non-repeatable reads & phantom reads.\n- Repeatable Read: Prevents dirty reads and non-repeatable reads; phantom reads are still possible.\n- Serializable: Prevents all anomalies including phantom reads.",
  },
  {
    title: "Computer Networks - TCP vs UDP Flow Control",
    category: "technical",
    type: "mcq",
    difficulty: "Easy",
    companies: ["google", "amazon", "microsoft", "cisco", "infosys", "tcs"],
    topics: ["Computer Networks", "Protocols", "TCP/IP"],
    frequency: "High",
    source: "Reported in Amazon, Microsoft & Cisco Networking tests",
    tags: ["Technical Interview", "Computer Networks", "2026"],
    lastReviewed: "2026",
    description: "Why is UDP (User Datagram Protocol) preferred over TCP for live video streaming and multiplayer online gaming?",
    options: [
      "UDP guarantees 100% in-order packet delivery without loss.",
      "UDP provides heavy encryption algorithms by default.",
      "UDP has minimal header overhead and does not introduce latency from retransmissions and 3-way handshakes.",
      "UDP requires continuous acknowledgment packets from the receiver."
    ],
    correctAnswer: 2,
    explanation: "UDP is connectionless and does not retransmit lost packets or maintain congested retransmission windows. This eliminates jitter and latency, making it ideal for real-time media (video calls, VoIP, gaming) where a slightly dropped frame is preferable to delayed video.",
  },
  {
    title: "SQL - WHERE vs HAVING Clause Execution Order",
    category: "technical",
    type: "mcq",
    difficulty: "Easy",
    companies: ["amazon", "microsoft", "adobe", "deloitte", "accenture", "tcs"],
    topics: ["DBMS", "SQL"],
    frequency: "High",
    source: "Reported in Deloitte & Amazon SQL technical rounds",
    tags: ["Technical Interview", "SQL", "2026"],
    lastReviewed: "2026",
    description: "What is the primary difference between the `WHERE` and `HAVING` clauses in SQL?",
    options: [
      "`WHERE` filters aggregated groups after GROUP BY, while `HAVING` filters individual rows before grouping.",
      "`WHERE` filters individual rows before grouping occurs, while `HAVING` filters aggregated groups after GROUP BY.",
      "`WHERE` can only be used with numeric data types.",
      "`HAVING` is faster than `WHERE` in all scenarios."
    ],
    correctAnswer: 1,
    explanation: "The `WHERE` clause filters individual row tuples BEFORE any grouping or aggregate functions (like `SUM()`, `AVG()`) take place. The `HAVING` clause filters aggregated group results AFTER the `GROUP BY` operation has been performed.",
  },
  {
    title: "Operating Systems - Virtual Memory & Page Faults",
    category: "technical",
    type: "mcq",
    difficulty: "Medium",
    companies: ["google", "microsoft", "amazon", "adobe", "tcs"],
    topics: ["Operating Systems", "Virtual Memory"],
    frequency: "High",
    source: "Reported in Google & Microsoft OS technical rounds",
    tags: ["Technical Interview", "OS", "2026"],
    lastReviewed: "2026",
    description: "When does a 'Page Fault' interrupt occur in an operating system?",
    options: [
      "When a process tries to write to read-only hardware ROM.",
      "When a referenced virtual memory page is not currently resident in physical RAM.",
      "When the CPU encounters a divide-by-zero hardware exception.",
      "When a deadlock is detected among active threads."
    ],
    correctAnswer: 1,
    explanation: "A Page Fault occurs when a program attempts to access a memory page mapped in its virtual address space, but that page is not currently loaded in physical main memory (RAM). The OS traps the fault, retrieves the page from secondary storage (swap/disk), updates the page table, and resumes execution.",
  },

  // ───────────────────────────────────────────────────────────────────────────
  // 4. CODING PROBLEMS (LeetCode-Style with Multi-Language Code & Test Cases)
  // ───────────────────────────────────────────────────────────────────────────
  {
    title: "Two Sum",
    category: "coding",
    type: "coding",
    difficulty: "Easy",
    companies: ["google", "amazon", "microsoft", "meta", "adobe", "tcs", "infosys"],
    topics: ["Array", "Hash Map", "Two Pointers"],
    frequency: "High",
    source: "Reported in Google, Amazon & Microsoft technical rounds",
    tags: ["OA", "Coding Interview", "2025", "2026"],
    lastReviewed: "2026",
    problemDescription: `Given an array of integers \`nums\` and an integer \`target\`, return *indices of the two numbers such that they add up to \`target\`*.

You may assume that each input would have ***exactly one solution***, and you may not use the same element twice.`,
    examples: [
      { input: "nums = [2,7,11,15], target = 9", output: "[0,1]", explanation: "Because nums[0] + nums[1] == 9, return [0, 1]." },
      { input: "nums = [3,2,4], target = 6", output: "[1,2]", explanation: "nums[1] + nums[2] == 6, return [1, 2]." },
    ],
    constraints: ["2 <= nums.length <= 10^4", "-10^9 <= nums[i] <= 10^9", "Only one valid answer exists."],
    starterCode: {
      javascript: `function twoSum(nums, target) {\n    // Write your code here\n}`,
      python: `class Solution:\n    def twoSum(self, nums: list[int], target: int) -> list[int]:\n        pass`,
      cpp: `class Solution {\npublic:\n    vector<int> twoSum(vector<int>& nums, int target) {\n        \n    }\n};`,
      java: `class Solution {\n    public int[] twoSum(int[] nums, int target) {\n        return new int[]{};\n    }\n}`
    },
    testCases: [
      { input: "[2,7,11,15]\n9", expectedOutput: "[0,1]", isHidden: false },
      { input: "[3,2,4]\n6", expectedOutput: "[1,2]", isHidden: false },
      { input: "[3,3]\n6", expectedOutput: "[0,1]", isHidden: true },
    ],
    hints: ["Use a Hash Map to store seen numbers: key=nums[i], val=i.", "Check if target - nums[i] already exists."],
    approach: `Single pass hash map lookup: O(n) time and O(n) space.`,
    solutionCode: {
      javascript: `function twoSum(nums, target) {\n    const seen = new Map();\n    for (let i = 0; i < nums.length; i++) {\n        const complement = target - nums[i];\n        if (seen.has(complement)) return [seen.get(complement), i];\n        seen.set(nums[i], i);\n    }\n    return [];\n}`,
      python: `class Solution:\n    def twoSum(self, nums: list[int], target: int) -> list[int]:\n        seen = {}\n        for i, num in enumerate(nums):\n            if target - num in seen:\n                return [seen[target - num], i]\n            seen[num] = i\n        return []`,
      cpp: `class Solution {\npublic:\n    vector<int> twoSum(vector<int>& nums, int target) {\n        unordered_map<int, int> seen;\n        for (int i = 0; i < nums.size(); i++) {\n            if (seen.count(target - nums[i])) return {seen[target - nums[i]], i};\n            seen[nums[i]] = i;\n        }\n        return {};\n    }\n};`,
      java: `class Solution {\n    public int[] twoSum(int[] nums, int target) {\n        HashMap<Integer, Integer> seen = new HashMap<>();\n        for (int i = 0; i < nums.length; i++) {\n            if (seen.containsKey(target - nums[i])) return new int[]{seen.get(target - nums[i]), i};\n            seen.put(nums[i], i);\n        }\n        return new int[]{};\n    }\n}`
    },
    timeComplexity: "O(n)",
    spaceComplexity: "O(n)",
  },
  {
    title: "Valid Parentheses",
    category: "coding",
    type: "coding",
    difficulty: "Easy",
    companies: ["google", "amazon", "microsoft", "meta", "adobe", "tcs", "infosys", "accenture"],
    topics: ["String", "Stack"],
    frequency: "High",
    source: "Reported in Microsoft, Amazon & Adobe technical rounds",
    tags: ["OA", "Stack", "2026"],
    lastReviewed: "2026",
    problemDescription: `Given a string \`s\` containing just the characters \`'('\`, \`')'\`, \`'{'\`, \`'}'\`, \`'['\` and \`']'\`, determine if the input string is valid.`,
    examples: [
      { input: 's = "()"', output: "true", explanation: "Valid parenthesis." },
      { input: 's = "()[]{}"', output: "true", explanation: "All matched." },
    ],
    constraints: ["1 <= s.length <= 10^4", "s consists of parentheses only."],
    starterCode: {
      javascript: `function isValid(s) {\n    // Write your code here\n}`,
      python: `class Solution:\n    def isValid(self, s: str) -> bool:\n        pass`,
      cpp: `class Solution {\npublic:\n    bool isValid(string s) {\n        \n    }\n};`,
      java: `class Solution {\n    public boolean isValid(String s) {\n        return false;\n    }\n}`
    },
    testCases: [
      { input: '"()"', expectedOutput: "true", isHidden: false },
      { input: '"(]"', expectedOutput: "false", isHidden: false },
      { input: '"{[]}"', expectedOutput: "true", isHidden: true },
    ],
    hints: ["Use a Stack to push expected closing brackets."],
    approach: `Use a stack to push matching brackets when an opener is found. Pop and match when closer is found.`,
    solutionCode: {
      javascript: `function isValid(s) {\n    const stack = [];\n    const map = { '(': ')', '{': '}', '[': ']' };\n    for (const c of s) {\n        if (map[c]) stack.push(map[c]);\n        else if (stack.pop() !== c) return false;\n    }\n    return stack.length === 0;\n}`,
      python: `class Solution:\n    def isValid(self, s: str) -> bool:\n        st = []\n        m = {'(': ')', '{': '}', '[': ']'}\n        for c in s:\n            if c in m: st.append(m[c])\n            elif not st or st.pop() != c: return False\n        return len(st) == 0`,
      cpp: `class Solution {\npublic:\n    bool isValid(string s) {\n        stack<char> st;\n        for (char c : s) {\n            if (c == '(') st.push(')');\n            else if (c == '{') st.push('}');\n            else if (c == '[') st.push(']');\n            else if (st.empty() || st.top() != c) return false;\n            else st.pop();\n        }\n        return st.empty();\n    }\n};`,
      java: `class Solution {\n    public boolean isValid(String s) {\n        Stack<Character> st = new Stack<>();\n        for (char c : s.toCharArray()) {\n            if (c == '(') st.push(')');\n            else if (c == '{') st.push('}');\n            else if (c == '[') st.push(']');\n            else if (st.isEmpty() || st.pop() != c) return false;\n        }\n        return st.isEmpty();\n    }\n}`
    },
    timeComplexity: "O(n)",
    spaceComplexity: "O(n)",
  },
  {
    title: "Container With Most Water",
    category: "coding",
    type: "coding",
    difficulty: "Medium",
    companies: ["google", "amazon", "meta", "adobe", "microsoft"],
    topics: ["Array", "Two Pointers", "Greedy"],
    frequency: "High",
    source: "Reported in Google & Amazon technical rounds",
    tags: ["Technical Interview", "Two Pointers", "2026"],
    lastReviewed: "2026",
    problemDescription: `You are given an integer array \`height\` of length \`n\`. There are \`n\` vertical lines drawn such that the two endpoints of the \`i\`th line are \`(i, 0)\` and \`(i, height[i])\`.

Find two lines that together with the x-axis form a container, such that the container contains the most water. Return *the maximum amount of water a container can store*.`,
    examples: [
      { input: "height = [1,8,6,2,5,4,8,3,7]", output: "49", explanation: "The max area is between index 1 and 8: min(8, 7) * 7 = 49." },
      { input: "height = [1,1]", output: "1", explanation: "Area = min(1, 1) * 1 = 1." }
    ],
    constraints: ["n == height.length", "2 <= n <= 10^5", "0 <= height[i] <= 10^4"],
    starterCode: {
      javascript: `function maxArea(height) {\n    // Write your code here\n}`,
      python: `class Solution:\n    def maxArea(self, height: list[int]) -> int:\n        pass`,
      cpp: `class Solution {\npublic:\n    int maxArea(vector<int>& height) {\n        \n    }\n};`,
      java: `class Solution {\n    public int maxArea(int[] height) {\n        return 0;\n    }\n}`
    },
    testCases: [
      { input: "[1,8,6,2,5,4,8,3,7]", expectedOutput: "49", isHidden: false },
      { input: "[1,1]", expectedOutput: "1", isHidden: false },
      { input: "[4,3,2,1,4]", expectedOutput: "16", isHidden: true },
    ],
    hints: ["Use two pointers at the ends (left=0, right=n-1).", "Move the pointer with the smaller height inward."],
    approach: `Two pointers starting from outside moving inward based on smaller height. Time: O(n), Space: O(1).`,
    solutionCode: {
      javascript: `function maxArea(height) {\n    let left = 0, right = height.length - 1, maxWater = 0;\n    while (left < right) {\n        const w = right - left;\n        const h = Math.min(height[left], height[right]);\n        maxWater = Math.max(maxWater, w * h);\n        if (height[left] < height[right]) left++;\n        else right--;\n    }\n    return maxWater;\n}`,
      python: `class Solution:\n    def maxArea(self, height: list[int]) -> int:\n        l, r = 0, len(height) - 1\n        max_water = 0\n        while l < r:\n            max_water = max(max_water, (r - l) * min(height[l], height[r]))\n            if height[l] < height[r]: l += 1\n            else: r -= 1\n        return max_water`,
      cpp: `class Solution {\npublic:\n    int maxArea(vector<int>& height) {\n        int l = 0, r = height.size() - 1, maxWater = 0;\n        while (l < r) {\n            maxWater = max(maxWater, (r - l) * min(height[l], height[r]));\n            if (height[l] < height[r]) l++;\n            else r--;\n        }\n        return maxWater;\n    }\n};`,
      java: `class Solution {\n    public int maxArea(int[] height) {\n        int l = 0, r = height.length - 1, maxWater = 0;\n        while (l < r) {\n            maxWater = Math.max(maxWater, (r - l) * Math.min(height[l], height[r]));\n            if (height[l] < height[r]) l++;\n            else r--;\n        }\n        return maxWater;\n    }\n}`
    },
    timeComplexity: "O(n)",
    spaceComplexity: "O(1)",
  },
  {
    title: "Valid Anagram",
    category: "coding",
    type: "coding",
    difficulty: "Easy",
    companies: ["tcs", "infosys", "accenture", "amazon", "google"],
    topics: ["String", "Hash Table", "Sorting"],
    frequency: "High",
    source: "Reported in TCS NQT, Infosys & Amazon OA",
    tags: ["OA", "String", "2026"],
    lastReviewed: "2026",
    problemDescription: `Given two strings \`s\` and \`t\`, return \`true\` *if \`t\` is an anagram of \`s\`, and \`false\` otherwise*.`,
    examples: [
      { input: 's = "anagram", t = "nagaram"', output: "true", explanation: "Both contain the same character counts." },
      { input: 's = "rat", t = "car"', output: "false", explanation: "Different character sets." }
    ],
    constraints: ["1 <= s.length, t.length <= 5 * 10^4", "s and t consist of lowercase English letters."],
    starterCode: {
      javascript: `function isAnagram(s, t) {\n    // Write your code here\n}`,
      python: `class Solution:\n    def isAnagram(self, s: str, t: str) -> bool:\n        pass`,
      cpp: `class Solution {\npublic:\n    bool isAnagram(string s, string t) {\n        \n    }\n};`,
      java: `class Solution {\n    public boolean isAnagram(String s, String t) {\n        return false;\n    }\n}`
    },
    testCases: [
      { input: '"anagram"\n"nagaram"', expectedOutput: "true", isHidden: false },
      { input: '"rat"\n"car"', expectedOutput: "false", isHidden: false },
      { input: '"a"\n"ab"', expectedOutput: "false", isHidden: true },
    ],
    hints: ["Count character frequencies using an array of size 26."],
    approach: `Array bucket frequency counter: O(n) time, O(1) extra space.`,
    solutionCode: {
      javascript: `function isAnagram(s, t) {\n    if (s.length !== t.length) return false;\n    const count = new Array(26).fill(0);\n    for (let i = 0; i < s.length; i++) {\n        count[s.charCodeAt(i) - 97]++;\n        count[t.charCodeAt(i) - 97]--;\n    }\n    return count.every(c => c === 0);\n}`,
      python: `class Solution:\n    def isAnagram(self, s: str, t: str) -> bool:\n        if len(s) != len(t): return False\n        count = [0] * 26\n        for c1, c2 in zip(s, t):\n            count[ord(c1) - 97] += 1\n            count[ord(c2) - 97] -= 1\n        return all(x == 0 for x in count)`,
      cpp: `class Solution {\npublic:\n    bool isAnagram(string s, string t) {\n        if (s.size() != t.size()) return false;\n        int count[26] = {0};\n        for (size_t i = 0; i < s.size(); i++) {\n            count[s[i] - 'a']++;\n            count[t[i] - 'a']--;\n        }\n        for (int c : count) if (c != 0) return false;\n        return true;\n    }\n};`,
      java: `class Solution {\n    public boolean isAnagram(String s, String t) {\n        if (s.length() != t.length()) return false;\n        int[] count = new int[26];\n        for (int i = 0; i < s.length(); i++) {\n            count[s.charAt(i) - 'a']++;\n            count[t.charAt(i) - 'a']--;\n        }\n        for (int c : count) if (c != 0) return false;\n        return true;\n    }\n}`
    },
    timeComplexity: "O(n)",
    spaceComplexity: "O(1)",
  },

  // ───────────────────────────────────────────────────────────────────────────
  // 5. INTERVIEW QUESTIONS (Technical, HR, Project Defense)
  // ───────────────────────────────────────────────────────────────────────────
  {
    title: "Explain the Core Principles of OOP",
    category: "interview",
    interviewCategory: "Technical",
    difficulty: "Easy",
    companies: ["google", "microsoft", "amazon", "adobe", "tcs", "infosys", "wipro", "accenture", "deloitte"],
    topics: ["OOP", "Core CS", "Java", "C++"],
    frequency: "High",
    source: "Reported in almost all campus technical interviews",
    tags: ["Technical Interview", "OOP", "2026"],
    lastReviewed: "2026",
    question: "Explain the four core principles of Object-Oriented Programming (OOP) with real-world examples.",
    whatInterviewerExpects: [
      "Clear definitions for Encapsulation, Abstraction, Inheritance, and Polymorphism.",
      "Concrete real-world analogies (e.g. Car accelerator/engine for abstraction, Bank account balance for encapsulation).",
      "Mentioning compile-time vs run-time polymorphism."
    ],
    importantPoints: [
      "1. Encapsulation: Bundling data and methods into classes with private access.",
      "2. Abstraction: Hiding internal complexity behind interfaces.",
      "3. Inheritance: Reusing code via parent-child class relationships.",
      "4. Polymorphism: Overloading (compile-time) and overriding (run-time)."
    ],
    sampleAnswer: `Object-Oriented Programming is built on four core pillars: Encapsulation (data hiding), Abstraction (simplifying interfaces), Inheritance (code reuse), and Polymorphism (dynamic behavior).`,
    tips: ["Always give a 1-sentence real-world analogy for each principle."],
  },
  {
    title: "Database Normalization (1NF to BCNF)",
    category: "interview",
    interviewCategory: "Technical",
    difficulty: "Medium",
    companies: ["amazon", "microsoft", "adobe", "tcs", "infosys", "deloitte"],
    topics: ["DBMS", "SQL", "Database Design"],
    frequency: "High",
    source: "Reported in Amazon SDE & Adobe Technical rounds",
    tags: ["Technical Interview", "DBMS", "2026"],
    lastReviewed: "2026",
    question: "What is database normalization? Explain 1NF, 2NF, 3NF and why denormalization is sometimes practiced in production.",
    whatInterviewerExpects: [
      "Anomalies prevented: Insertion, Update, and Deletion.",
      "Definitions of 1NF, 2NF, and 3NF.",
      "Why high-scale OLAP systems denormalize to reduce JOIN latency."
    ],
    importantPoints: [
      "1NF: Atomic values.",
      "2NF: No partial functional dependencies.",
      "3NF: No transitive functional dependencies.",
      "Denormalization: Trade-off between write integrity vs read throughput."
    ],
    sampleAnswer: `Normalization organizes schemas to eliminate data redundancy and anomalies (1NF = atomic columns, 2NF = full primary key dependency, 3NF = no transitive dependencies). In high-scale reads, selective denormalization removes expensive multi-table JOINs.`,
    tips: ["Illustrate with an Employee-Department example."],
  },
  {
    title: "Explain the CAP Theorem in Distributed Systems",
    category: "interview",
    interviewCategory: "Technical",
    difficulty: "Hard",
    companies: ["google", "amazon", "microsoft", "meta", "adobe"],
    topics: ["System Design", "Distributed Systems", "Databases"],
    frequency: "High",
    source: "Reported in Google & Amazon System Architecture rounds",
    tags: ["Technical Interview", "System Design", "2026"],
    lastReviewed: "2026",
    question: "Explain the CAP Theorem. Why is it impossible to achieve all three in a distributed system during network partitions?",
    whatInterviewerExpects: [
      "Definitions of Consistency, Availability, and Partition Tolerance.",
      "Understanding that network partitions (P) are physically unavoidable.",
      "CP vs AP real-world database examples (MongoDB vs Cassandra)."
    ],
    importantPoints: [
      "Consistency (C): Every read gets latest write.",
      "Availability (A): Every request gets non-error response.",
      "Partition Tolerance (P): Non-negotiable in real networks.",
      "CP = consistent but blocks partitioned nodes; AP = available but serves eventual consistency."
    ],
    sampleAnswer: `The CAP Theorem establishes that during inevitable network partitions (P), a distributed system must choose between serving consistent latest data (CP - e.g. MongoDB/Spanner) or remaining available with eventual consistency (AP - e.g. Cassandra/DynamoDB).`,
    tips: ["Explain PACELC extension if interviewing for product companies."],
  },
  {
    title: "Tell Me About Yourself (Elevator Pitch)",
    category: "interview",
    interviewCategory: "HR",
    difficulty: "Easy",
    companies: ["google", "microsoft", "amazon", "meta", "adobe", "tcs", "infosys", "wipro", "accenture", "deloitte"],
    topics: ["HR", "Behavioral", "Self Introduction"],
    frequency: "High",
    source: "The universal opening question in every HR and Technical interview",
    tags: ["HR Interview", "Behavioral", "2026"],
    lastReviewed: "2026",
    question: "Walk me through your background and tell me about yourself.",
    whatInterviewerExpects: [
      "A structured 90-120 second pitch following Present -> Past -> Future.",
      "Highlighting DSA + fullstack projects.",
      "Enthusiasm for the company."
    ],
    importantPoints: ["Present stack, Past achievements/projects, Future alignment with company."],
    sampleAnswer: `I am a final-year CS student specializing in fullstack engineering (React, Node.js, MongoDB) and algorithmic problem solving in C++ (350+ DSA problems). Recently, I built Anva, a real-time collaborative platform with WebRTC and sandboxed code execution. I am excited to bring my development velocity and passion for scalable systems to your engineering team.`,
    tips: ["Keep it strictly under 2 minutes."],
  },
];

export const seedPlacementData = async () => {
  try {
    const existingCompanies = await PlacementCompany.countDocuments();
    if (existingCompanies === 0) {
      console.log("🌱 Seeding Placement Companies...");
      await PlacementCompany.insertMany(COMPANIES_DATA);
      console.log(`✅ Seeded ${COMPANIES_DATA.length} Placement Companies.`);
    } else {
      for (const comp of COMPANIES_DATA) {
        await PlacementCompany.updateOne(
          { slug: comp.slug },
          { $set: comp },
          { upsert: true }
        );
      }
    }

    const allQuestions = [
      ...SAMPLE_QUESTIONS,
      ...APTITUDE_QUESTIONS,
      ...TECHNICAL_QUESTIONS,
      ...CODING_QUESTIONS,
      ...NEW_MNC_QUESTIONS,
      ...PLACEMENT_2026_QUESTIONS,
      ...CODING_2026_QUESTIONS,
      ...INTERVIEW_QUESTIONS_DATA,
    ];
    console.log(`🌱 Synchronizing ${allQuestions.length} Placement Questions across all categories...`);
    
    for (const q of allQuestions) {
      await PlacementQuestion.updateOne(
        { title: q.title, category: q.category },
        { $set: q },
        { upsert: true }
      );
    }

    const totalQuestions = await PlacementQuestion.countDocuments();
    console.log(`🎯 Placement Hub Synced: ${totalQuestions} Total Placement Questions in database.`);
  } catch (error) {
    console.error("❌ Error in seedPlacementData:", error);
  }
};
