const quotes = {
  spanish: [
    "El único modo de hacer un gran trabajo es amar lo que haces.",
    "No importa lo lento que vayas mientras no te detengas.",
    "El éxito no es final, el fracaso no es fatal.",
    "La educación es el arma más poderosa.",
    "Siempre parece imposible hasta que se hace.",
    "Cree que puedes y estarás a mitad de camino.",
    "Duda mata más sueños que el fracaso.",
    "Haz lo que puedas, con lo que tengas, donde estés.",
    "El conocimiento es poder.",
    "Sé el cambio que quieres ver en el mundo.",
    "La disciplina es el puente entre metas y logros.",
    "Nunca es demasiado tarde para ser lo que podrías haber sido.",
    "La acción es la clave fundamental de todo éxito.",
    "El futuro pertenece a los que creen en la belleza de sus sueños.",
    "No cuentes los días, haz que los días cuenten.",
    "La mejor manera de predecir el futuro es crearlo.",
    "Si no puedes hacer grandes cosas, haz cosas pequeñas de una gran manera.",
    "El fracaso es solo la oportunidad de comenzar de nuevo de forma más inteligente.",
    "Lo único imposible es aquello que no intentas.",
    "Piensa, cree, sueña y atrévete."
  ],
  french: [
    "La seule façon de faire du bon travail est d'aimer ce que vous faites.",
    "Peu importe la lenteur à laquelle vous allez tant que vous ne vous arrêtez pas.",
    "Le succès n'est pas final, l'échec n'est pas fatal.",
    "L'éducation est l'arme la plus puissante.",
    "Cela semble toujours impossible jusqu'à ce que ce soit fait.",
    "Croyez que vous le pouvez et vous êtes à la moitié du chemin.",
    "Le doute tue plus de rêves que l'échec.",
    "Faites ce que vous pouvez, avec ce que vous avez, là où vous êtes.",
    "Le savoir est le pouvoir.",
    "Soyez le changement que vous voulez voir dans le monde.",
    "La discipline est le pont entre les objectifs et les réalisations.",
    "Il n'est jamais trop tard pour être ce que vous auriez pu être.",
    "L'action est la clé fondamentale de tout succès.",
    "L'avenir appartient à ceux qui croient à la beauté de leurs rêves.",
    "Ne comptez pas les jours, faites que les jours comptent.",
    "La meilleure façon de prédire l'avenir est de le créer.",
    "Si vous ne pouvez pas faire de grandes choses, faites de petites choses de façon grandiose.",
    "L'échec est seulement l'opportunité de recommencer plus intelligemment.",
    "La seule chose impossible est celle que vous ne tentez pas.",
    "Pensez, croyez, rêvez et osez."
  ],
  german: [
    "Der einzige Weg, großartige Arbeit zu leisten, ist zu lieben, was man tut.",
    "Es spielt keine Rolle, wie langsam du gehst, solange du nicht stehen bleibst.",
    "Erfolg ist nicht endgültig, Misserfolg ist nicht tödlich.",
    "Bildung ist die mächtigste Waffe.",
    "Es scheint immer unmöglich, bis es vollbracht ist.",
    "Glaube daran, dass du es kannst, und du hast die halbe Miete.",
    "Zweifel tötet mehr Träume als Versagen.",
    "Tu, was du kannst, mit dem, was du hast, wo immer du bist.",
    "Wissen ist Macht.",
    "Sei die Veränderung, die du in der Welt sehen willst.",
    "Disziplin ist die Brücke zwischen Zielen und Erfolg.",
    "Es ist nie zu spät, das zu sein, was man hätte sein können.",
    "Handeln ist der grundlegende Schlüssel zu allem Erfolg.",
    "Die Zukunft gehört denen, die an die Schönheit ihrer Träume glauben.",
    "Zähle nicht die Tage, mach, dass die Tage zählen.",
    "Der beste Weg, die Zukunft vorauszusagen, ist, sie zu erfinden.",
    "Wenn du keine großen Dinge tun kannst, tue kleine Dinge auf großartige Weise.",
    "Scheitern ist einfach die Gelegenheit, von vorn zu beginnen, diesmal intelligenter.",
    "Das einzig Unmögliche ist das, was du nicht versuchst.",
    "Denke, glaube, träume und wage."
  ],
  italian: [
    "L'unico modo per fare un ottimo lavoro è amare quello che fai.",
    "Non importa quanto vai piano, l'importante è non fermarsi.",
    "Il successo non è definitivo, il fallimento non è fatale.",
    "L'istruzione è l'arma più potente.",
    "Sembra sempre impossibile finché non viene fatto.",
    "Credi di potercela fare e sei a metà dell'opera.",
    "Il dubbio uccide più sogni di quanto faccia mai il fallimento.",
    "Fai quello che puoi, con quello che hai, nel posto in cui sei.",
    "La conoscenza è potere.",
    "Sii il cambiamento che vuoi vedere nel mondo.",
    "La disciplina è il ponte tra gli obiettivi e le realizzazioni.",
    "Non è mai troppo tardi per essere ciò che avresti potuto essere.",
    "L'azione è la chiave fondamentale di ogni successo.",
    "Il futuro appartiene a coloro che credono nella bellezza dei propri sogni.",
    "Non contare i giorni, fai in modo che i giorni contino.",
    "Il modo migliore per predire il futuro è crearlo.",
    "Se non puoi fare cose grandi, fai cose piccole in modo grandioso.",
    "Il fallimento è solo l'opportunità di ricominciare in modo più intelligente.",
    "L'unica cosa impossibile è quella che non provi a fare.",
    "Pensa, credi, sogna e osa."
  ],
  japanese: [
    "偉大な仕事をする唯一の方法は、自分のしていることを愛することだ。",
    "止まらない限り、どんなにゆっくり進んでも構わない。",
    "成功は決定的ではなく、失敗は致命的ではない。",
    "教育は最も強力な武器である。",
    "何事も達成するまでは不可能に見える。",
    "できると信じれば、半分は終わったようなものだ。",
    "疑いは失敗よりも多くの夢を殺す。",
    "今あるもので、今いる場所で、できることをしなさい。",
    "知識は力なり。",
    "あなた自身が、世界に見たい変化でありなさい。",
    "規律は目標と達成の架け橋である。",
    "なりたかった自分になるのに、遅すぎることはない。",
    "行動はすべての成功の基本的な鍵である。",
    "未来は、夢の美しさを信じる者のためにある。",
    "日数を数えるな、日数を有意義なものにしろ。",
    "未来を予測する最良の方法は、それを創り出すことだ。",
    "偉大なことができないなら、小さなことを偉大な方法でやりなさい。",
    "失敗とは、より賢く再挑戦するための機会に過ぎない。",
    "唯一の不可能とは、挑戦しないことである。",
    "考え、信じ、夢見て、挑戦せよ。"
  ],
  english: [
    "The only way to do great work is to love what you do.",
    "It does not matter how slowly you go as long as you do not stop.",
    "Success is not final, failure is not fatal.",
    "Education is the most powerful weapon.",
    "It always seems impossible until it's done.",
    "Believe you can and you're halfway there.",
    "Doubt kills more dreams than failure ever will.",
    "Do what you can, with what you have, where you are.",
    "Knowledge is power.",
    "Be the change that you wish to see in the world.",
    "Discipline is the bridge between goals and accomplishment.",
    "It is never too late to be what you might have been.",
    "Action is the foundational key to all success.",
    "The future belongs to those who believe in the beauty of their dreams.",
    "Don't count the days, make the days count.",
    "The best way to predict the future is to create it.",
    "If you cannot do great things, do small things in a great way.",
    "Failure is simply the opportunity to begin again, this time more intelligently.",
    "The only impossible journey is the one you never begin.",
    "Think, believe, dream, and dare."
  ]
};

export const getRandomLanguageQuote = (language) => {
  const normalizedLang = language?.toLowerCase() || 'english';
  const langQuotes = quotes[normalizedLang] || quotes['english'];
  return langQuotes[Math.floor(Math.random() * langQuotes.length)];
};
