export const MOTIVATIONAL_QUOTES = [
  "The only way to do great work is to love what you do. – Steve Jobs",
  "It does not matter how slowly you go as long as you do not stop. – Confucius",
  "First, solve the problem. Then, write the code. – John Johnson",
  "Code is like humor. When you have to explain it, it’s bad. – Cory House",
  "Make it work, make it right, make it fast. – Kent Beck",
  "Experience is the name everyone gives to their mistakes. – Oscar Wilde",
  "In software, the most beautiful code is the code you don't have to write.",
  "Programming isn't about what you know; it's about what you can figure out. – Chris Pine",
  "The best error message is the one that never shows up. – Thomas Fuchs",
  "Simplicity is the soul of efficiency. – Austin Freeman",
  "Before software can be reusable it first has to be usable. – Ralph Johnson",
  "Optimism is an occupational hazard of programming. – Kent Beck",
  "Sometimes it pays to stay in bed on Monday, rather than spending the rest of the week debugging Monday's code. – Dan Salomon",
  "Fix the cause, not the symptom. – Steve Maguire",
  "Truth can only be found in one place: the code. – Robert C. Martin",
  "The most important property of a program is whether it accomplishes the intention of its user. – C.A.R. Hoare",
  "Ruby is rubbish! PHP is phpantastic! – Nikita Popov",
  "I'm not a great programmer; I'm just a good programmer with great habits. – Kent Beck",
  "Don't worry if it doesn't work right. If everything did, you'd be out of a job. – Mosher's Law",
  "A good programmer is someone who always looks both ways before crossing a one-way street. – Doug Linder",
  "Learning to write programs stretches your mind, and helps you think better. – Bill Gates",
  "Talk is cheap. Show me the code. – Linus Torvalds",
  "Any fool can write code that a computer can understand. Good programmers write code that humans can understand. – Martin Fowler",
  "If you optimize everything, you will always be unhappy. – Donald Knuth",
  "Programs must be written for people to read, and only incidentally for machines to execute. – Harold Abelson",
  "Give a man a program, frustrate him for a day. Teach a man to program, frustrate him for a lifetime. – Muhammad Waseem",
  "The function of good software is to make the complex appear to be simple. – Grady Booch",
  "Your most unhappy customers are your greatest source of learning. – Bill Gates",
  "Perfection is achieved not when there is nothing more to add, but rather when there is nothing more to take away. – Antoine de Saint-Exupery",
  "Design is not just what it looks like and feels like. Design is how it works. – Steve Jobs",
  "You might not think that programmers are artists, but programming is an extremely creative profession. – John Romero",
  "Every great developer you know got there by solving problems they were unqualified to solve until they actually did it. – Patrick McKenzie",
  "Success is not final, failure is not fatal: it is the courage to continue that counts. – Winston Churchill",
  "What you do today can improve all your tomorrows. – Ralph Marston",
  "Do something today that your future self will thank you for.",
  "It always seems impossible until it's done. – Nelson Mandela",
  "Believe you can and you're halfway there. – Theodore Roosevelt",
  "The future depends on what you do today. – Mahatma Gandhi",
  "You don't have to be great to start, but you have to start to be great. – Zig Ziglar",
  "I have not failed. I've just found 10,000 ways that won't work. – Thomas Edison",
  "Don't watch the clock; do what it does. Keep going. – Sam Levenson",
  "Start where you are. Use what you have. Do what you can. – Arthur Ashe",
  "The expert in anything was once a beginner. – Helen Hayes",
  "Continuous improvement is better than delayed perfection. – Mark Twain",
  "Focus on being productive instead of busy. – Tim Ferriss",
  "Success is walking from failure to failure with no loss of enthusiasm. – Winston Churchill",
  "Opportunities don't happen. You create them. – Chris Grosser",
  "Don't wait for inspiration. It comes while working. – Henri Matisse",
  "A year from now you may wish you had started today. – Karen Lamb",
  "If you want to achieve greatness stop asking for permission.",
  "The secret of getting ahead is getting started. – Mark Twain",
  "Doubt kills more dreams than failure ever will. – Suzy Kassem",
  "Things work out best for those who make the best of how things work out. – John Wooden",
  "If you are not willing to risk the usual, you will have to settle for the ordinary. – Jim Rohn",
  "Stop chasing the money and start chasing the passion. – Tony Hsieh",
  "All our dreams can come true if we have the courage to pursue them. – Walt Disney",
  "The mind is just like a muscle - the more you exercise it, the stronger it gets. – Idowu Koyenikan",
  "Whether you think you can or you think you can't, you're right. – Henry Ford",
  "Do what you can with all you have, wherever you are. – Theodore Roosevelt",
  "You are never too old to set another goal or to dream a new dream. – C.S. Lewis",
  "Reading is to the mind what exercise is to the body. – Joseph Addison",
  "Knowledge is power. – Francis Bacon",
  "The capacity to learn is a gift; the ability to learn is a skill; the willingness to learn is a choice. – Brian Herbert",
  "Education is the most powerful weapon which you can use to change the world. – Nelson Mandela",
  "Anyone who stops learning is old, whether at twenty or eighty. – Henry Ford",
  "An investment in knowledge pays the best interest. – Benjamin Franklin",
  "Programming is thinking, not typing. – Casey Muratori",
  "Testing leads to failure, and failure leads to understanding. – Burt Rutan",
  "There is nothing quite so useless as doing with great efficiency something that should not be done at all. – Peter Drucker",
  "Programming is a skill best acquired by practice and example rather than from books. – Alan Turing",
  "If debugging is the process of removing software bugs, then programming must be the process of putting them in. – Edsger Dijkstra",
  "Software is a great combination between artistry and engineering. – Bill Gates",
  "The best way to predict the future is to invent it. – Alan Kay",
  "Make it simple, but significant. – Don Draper",
  "Small daily improvements over time lead to stunning results. – Robin Sharma",
  "Motivation is what gets you started. Habit is what keeps you going. – Jim Ryun",
  "Discipline is the bridge between goals and accomplishment. – Jim Rohn",
  "Success usually comes to those who are too busy to be looking for it. – Henry David Thoreau",
  "Hard work beats talent when talent doesn't work hard. – Tim Notke",
  "The only place where success comes before work is in the dictionary. – Vidal Sassoon",
  "There are no shortcuts to any place worth going. – Beverly Sills",
  "Strive for progress, not perfection.",
  "The struggle you're in today is developing the strength you need for tomorrow.",
  "Your limitation—it's only your imagination.",
  "Push yourself, because no one else is going to do it for you.",
  "Great things never come from comfort zones.",
  "Dream it. Wish it. Do it.",
  "Success doesn’t just find you. You have to go out and get it.",
  "The harder you work for something, the greater you’ll feel when you achieve it.",
  "Dream bigger. Do bigger.",
  "Don’t stop when you’re tired. Stop when you’re done.",
  "Wake up with determination. Go to bed with satisfaction.",
  "Little things make big days.",
  "It’s going to be hard, but hard does not mean impossible.",
  "Don’t wait for opportunity. Create it.",
  "Sometimes we’re tested not to show our weaknesses, but to discover our strengths.",
  "The key to success is to focus on goals, not obstacles.",
  "Dream it. Believe it. Build it.",
  "Quality is not an act, it is a habit. – Aristotle",
  "You don't learn to walk by following rules. You learn by doing, and by falling over. – Richard Branson",
  "To sit back and let fate play its hand out and never influence it is not the way man was meant to operate. – John Glenn"
];
